project_name: mcpproxy
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # macOS universal binary for GUI/tray support (CGO enabled)
  - id: mac
    env:
      - CGO_ENABLED=1
      - GOFLAGS=-trimpath
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/mcpproxy
    binary: mcpproxy
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -H=darwin
    
  # GUI builds with tray support (CGO enabled) - Linux/Windows
  - id: gui
    env:
      - CGO_ENABLED=1
      - GOFLAGS=-trimpath
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/mcpproxy
    binary: mcpproxy
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    ignore:
      # Skip some problematic combinations for GUI builds
      - goos: linux
        goarch: arm64
  
  # Headless builds without tray support (CGO disabled)
  - id: headless
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-trimpath
    tags:
      - nogui
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/mcpproxy
    binary: mcpproxy-headless
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  # macOS-specific archive for DMG creation
  - id: maczip
    builds: [mac]
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      macOS_universal
    files:
      - README.md
      - LICENSE*
      - assets/icons/icon.svg
      
  # Regular archives for other platforms
  - id: default
    builds: [gui, headless]
    format: tar.gz
    # Use zip for Windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: smart-mcp-proxy
    name: mcpproxy-go
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## mcpproxy {{ .Tag }}
    
    Smart MCP Proxy - Intelligent tool discovery and proxying for Model Context Protocol servers.

    ### Installation

    #### macOS
    - **DMG**: Download `mcpproxy-{{ .Tag }}.dmg` for drag-and-drop installation
    - **Homebrew**: `brew install smart-mcp-proxy/tap/mcpproxy`
    - **First Launch**: Right-click → Open to bypass Gatekeeper (unsigned app)

    #### Auto-update
    If you have a previous version installed with system tray enabled, you can update directly from the tray menu by clicking "Check for Updates...".

  footer: |
    ## Installation

    ### Direct Download
    Download the appropriate binary for your platform from the assets below.

    ### Using Go
    ```bash
    go install github.com/smart-mcp-proxy/mcpproxy-go/cmd/mcpproxy@{{ .Tag }}
    ```

    ## What's Changed
  name_template: "{{.ProjectName}}-{{.Version}}"

# Use homebrew_casks instead of brews for v2 (brews is deprecated)
homebrew_casks:
  - name: mcpproxy
    repository:
      owner: smart-mcp-proxy
      name: homebrew-tap
    directory: Casks  # Changed from 'folder' to 'directory'
    homepage: https://github.com/smart-mcp-proxy/mcpproxy-go
    description: Smart MCP Proxy - Intelligent tool discovery and proxying for Model Context Protocol servers
    # Add post-install hook to remove quarantine for unsigned binaries
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpproxy"]
          end

# Optional: Windows package manager
winget:
  - name: mcpproxy
    publisher: smart-mcp-proxy
    license: MIT
    homepage: https://github.com/smart-mcp-proxy/mcpproxy-go
    description: Smart MCP Proxy - Intelligent tool discovery and proxying for Model Context Protocol servers
    repository:
      owner: smart-mcp-proxy
      name: winget-pkgs
      branch: mcpproxy-{{.Version}}
      pull_request:
        enabled: true
        base:
          branch: master

# Optional: Linux packages
nfpms:
  - id: mcpproxy
    package_name: mcpproxy
    vendor: smart-mcp-proxy
    homepage: https://github.com/smart-mcp-proxy/mcpproxy-go
    maintainer: smart-mcp-proxy <maintainer@smart-mcp-proxy.com>
    description: Smart MCP Proxy - Intelligent tool discovery and proxying for Model Context Protocol servers
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    
    contents:
      # Optional: Add systemd service file
      - src: ./scripts/mcpproxy.service
        dst: /etc/systemd/system/mcpproxy.service
        type: config
    
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh

# Note: DMG creation is only available in GoReleaser Pro
# Removed dmg configuration as it's not supported in the free version

# Docker images (optional)
dockers:
  - image_templates:
      - "ghcr.io/smart-mcp-proxy/mcpproxy:{{ .Version }}-amd64"
      - "ghcr.io/smart-mcp-proxy/mcpproxy:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/smart-mcp-proxy/mcpproxy:{{ .Version }}-arm64"
      - "ghcr.io/smart-mcp-proxy/mcpproxy:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/smart-mcp-proxy/mcpproxy:{{ .Version }}"
    image_templates:
      - "ghcr.io/smart-mcp-proxy/mcpproxy:{{ .Version }}-amd64"
      - "ghcr.io/smart-mcp-proxy/mcpproxy:{{ .Version }}-arm64"
  
  - name_template: "ghcr.io/smart-mcp-proxy/mcpproxy:latest"
    image_templates:
      - "ghcr.io/smart-mcp-proxy/mcpproxy:latest-amd64"
      - "ghcr.io/smart-mcp-proxy/mcpproxy:latest-arm64" 